name: Build debug
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - '.github/**'
      - 'app/**'
      - 'gradle/**'
      - '*.properties'
      - '*.gradle'
      - 'gradlew'
      - 'gradlew.bat'

jobs:
  generate-debug-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Download gradle dependencies
        run: ./gradlew dependencies

      - name: Build debug app
        run: ./gradlew :app:assembleDebug

      - name: Send APK to Telegram
        run: release/deploy-telegram.sh
        env:
          TG_TO: ${{ secrets.TELEGRAM_TO }}
          TG_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TG_FILE: ./app/build/outputs/apk/debug/app-debug.apk